server:
  port: 8889
spring:
  datasource:
    username: root
    password: TEST1234mysql
    url: jdbc:mysql://localhost:3306/bill?serverTimezone=UTC&characterEncoding=utf-8
    driver-class-name: com.mysql.cj.jdbc.Driver
    initialization-mode: always
    schema: classpath:schema.sql
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER
mybatis:
  mapper-locations: classpath:mybatis/mapper/*.xml
  type-aliases-package: pers.jasper.bill
  configuration:
    map-underscore-to-camel-case: true